# Generated by Django 3.1.5 on 2021-01-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0007_auto_20210129_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
