# Generated by Django 3.1.5 on 2021-01-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0009_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
