# Generated by Django 3.1.5 on 2021-02-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0010_remove_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='note_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
